language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
script:
  - mvn clean integration-test -P full
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app:
    master: netcracker-2017-habitaria
    dev: netcracker-2017-habitaria-dev
notifications:
  slack: netcracker-2017-team:Ofl5gqjMXYz2h1VW4595QjhA