spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:hsqldb:mem:dataSource
    username: sa
    password: ""
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    rest:
      basePath: "/api"